# theme
# ??????
theme = "LoveIt"
# themes directory
# ????????????
themesDir = "../.."

# website title
# ???????????? 
title = "LoveIt"

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
# ????????????????????? ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
# language code ["en", "zh-CN", "fr", "pl", ...]
# ????????????, ???????????? CN ?????? ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "????????????", "Fran??ais", "Polski", ...]
# ???????????? ["English", "????????????", "Fran??ais", "Polski", ...] 
languageName = "English"
# whether to include Chinese/Japanese/Korean
# ???????????????????????????
hasCJKLanguage = false

# default amount of posts in each pages
# ???????????????????????????????????????
paginate = 12
# google analytics code [UA-XXXXXXXX-X]
# ?????????????????? [UA-XXXXXXXX-X]   
googleAnalytics = ""
# copyright description used only for seo schema
# ??????????????????????????? SEO
copyright = ""

# whether to use robots.txt
# ???????????? robots.txt  
enableRobotsTXT = true   
# whether to use git commit log
# ???????????? git ??????
enableGitInfo = true
# whether to use emoji code
# ???????????? emoji ??????
enableEmoji = true

# ignore some build errors
# ????????????????????????
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# ^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Pg   ^K Cut Text  ^C Cur Pos   

